#ifndef clox_debug_h
#define clox_debug_h

#include "chunk.h"

/**
 * Disassemble an entire chunk.
 * This allows to debug the generated bytecode.
 **/
void disassembleChunk (Chunk * chunk, const char * name);
/**
 * Disassemble a single instruction in a chunk.
 **/
int disassembleInstruction (Chunk * chunk, int offset);

#endif
